refarch:
  security:
    sso-issuer-url: http://keycloak:8100/auth/realms/local_realm
  s3:
    bucket-name: test-bucket
    access-key: minio
    secret-key: Test1234
    url: http://localhost:9000
server:
  port: 8086
