SSO_ISSUER_URL: http://keycloak:8100/auth/realms/local_realm
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SSO_ISSUER_URL}
security:
  oauth2:
    resource:
      user-info-uri: ${SSO_ISSUER_URL}/protocol/openid-connect/userinfo
refarch:
  s3:
    bucket-name: test-bucket
    access-key: minio
    secret-key: Test1234
    url: http://localhost:9000
server:
  port: 8086
