changelog:
  categories:
    - title: 🎉 New Features
      labels:
        - feature
    - title: 🐞 Bug Fixes
      labels:
        - bug
    - title: 🔨 Refactoring
      labels:
        - refactoring
    - title: 📔 Documentation
      labels:
        - docs
    - title: 🔨 Dependency Upgrades
      labels:
        - dependencies
