refarch:
  security:
    client-registration: keycloak
    permitted-urls:
      - /error # allow the error page
      - /actuator/info # allow access to /actuator/info
      - /actuator/health #  allow access to /actuator/health for OpenShift Health Check
      - /actuator/metrics # allow access to /actuator/metrics for Prometheus monitoring in OpenShift
      - /actuator/prometheus # allow access to /actuator/prometheus for Prometheus monitoring in OpenShift
      - /swagger-ui/index.html # allow access to swagger
      - /swagger-ui*/*swagger-initializer.js # allow access to swagger
      - /swagger-ui*/** # allow access to swagger
      - /v3/api-docs/* # allow access to swagger
      - /v3/api-docs # allow access to swagger
    service-account: true


spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SSO_ISSUER_URL}
      client:
        provider:
          keycloak:
            issuer-uri: ${SSO_ISSUER_URL}
            user-info-uri: ${SSO_BASE_URL}/realms/${SSO_REALM}/protocol/openid-connect/userinfo
            jwk-set-uri: ${SSO_BASE_URL}/realms/${SSO_REALM}/protocol/openid-connect/certs
            user-name-attribute: lhmObjectID
        registration:
          keycloak:
            provider: keycloak
            client-id: ${refarch.security.client-id}
            client-secret: ${refarch.security.client-secret}
            scope: email, profile, openid  # needed for userInfo endpoint
          keycloak-service-account:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: ${refarch.security.client-id}
            client-secret: ${refarch.security.client-secret}
            scope: email, profile, openid  # needed for userInfo endpoint
