spring:
  cloud:
    function:
      definition: functionRouter;sendMessage;
    stream:
      function:
        routing:
          enabled: 'true'
      kafka:
        binder:
          producerProperties:
            value:
              serializer: org.springframework.kafka.support.serializer.JsonSerializer
            key:
              serializer: org.springframework.kafka.support.serializer.JsonSerializer
          consumerProperties:
            key:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            auto:
              offset:
                reset: latest
          configuration:
            security:
              #protocol: SSL
          brokers: ${KAFKA_BOOTSTRAP_SERVER:localhost}:${KAFKA_BOOTSTRAP_SERVER_PORT:29092}

      bindings:
        functionRouter-in-0:
          group: "dwf-cosys-service"
          destination: "dwf-cosys-${DIGIWF_ENV}"
        sendMessage-out-0:
          destination: "dwf-connector-${DIGIWF_ENV}"
  kafka:
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: "*"

io:
  muenchendigital:
    digiwf:
      message:
        incidentDestination: "dwf-connector-incident-${DIGIWF_ENV}"
        bpmnErrorDestination: "dwf-connector-bpmnerror-${DIGIWF_ENV}"
        correlateMessageDestination: "dwf-connector-${DIGIWF_ENV}"