name: refarch-development-stack

x-healthcheck: &healthcheck
  interval: 30s
  timeout: 60s
  retries: 3
  start_period: 60s

x-security-settings: &security_settings
  security_opt:
    - no-new-privileges:true

services:
  # === Keycloak ===
  keycloak:
    image: quay.io/keycloak/keycloak:26.6.4@sha256:0aae0de7fca85525f727d3354df17896092de8bb26ae4c12d89c77e5df8cbce4
    command:
      - start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_HTTP_PORT: 8100
      KC_HTTP_RELATIVE_PATH: /auth
    ports:
      - "8100:8100"
    networks:
      - keycloak
    healthcheck:
      <<: *healthcheck
      test: [
        "CMD-SHELL",
        # health check see https://www.keycloak.org/observability/health#_healthcheck
        "{ printf 'HEAD /auth/health/ready HTTP/1.0\r\n\r\n' >&0; grep 'HTTP/1.0 200'; } 0<>/dev/tcp/localhost/9000"
      ]
    <<: *security_settings

  init-keycloak:
    image: klg71/keycloakmigration:0.2.130@sha256:fbec0fbbec2f90e9e912576cfb2ff108fb5703a59383b5e51c8633c130173af8
    depends_on:
      - keycloak
    environment:
      ADMIN_USER: admin
      ADMIN_PASSWORD: admin
      BASEURL: http://keycloak:8100/auth
      WAIT_FOR_KEYCLOAK: "true"
      FAIL_ON_UNDEFINED_VARIABLES: "true"
      KEYCLOAK_CHANGELOG: /migration/keycloak-changelog.yml
      EXIT_ON_ERROR: "true"
    volumes:
      - ./keycloak/migration:/migration
    networks:
      - keycloak
    <<: *security_settings

  # === Redis ===
  redis:
    image: redis:8.8.1-alpine@sha256:8096655e437712b07503796fb64d81359256cfcff0ab29d95a7da72863786efb
    ports:
      - "6379:6379"
    healthcheck:
      <<: *healthcheck
      test: [ "CMD-SHELL",  "redis-cli ping" ]
    <<: *security_settings

  # === S3 ===
  minio:
    image: quay.io/minio/minio:RELEASE.2024-08-17T01-24-54Z@sha256:6f23072e3e222e64fe6f86b31a7f7aca971e5129e55cbccef649b109b8e651a1
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: Test1234
    ports:
      - "9000:9000" # API
      - "9001:9001" # UI
    volumes:
      - ./minio:/data
    networks:
      - minio
    healthcheck:
      <<: *healthcheck
      test: [ "CMD-SHELL",  "curl http://localhost:9000/minio/health/live" ]
    <<: *security_settings

  init-minio:
    image: minio/mc:RELEASE.2024-08-17T11-33-50Z@sha256:87382ad79da9f464a444aab607b3db9251c7fe7d1bfda0eb86cbacee2ca2b564
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        mc config host add minio http://minio:9000 minio Test1234;
        mc mb minio/test-bucket;
        exit 0;
      "
    networks:
      - minio
    <<: *security_settings

  # === Mail ===
  mailpit:
    image: axllent/mailpit:v1.31.0@sha256:c96991d9bef73594c246d89ca81411d4e916f03e76a7d2d72fa2ab5dd3c9ce24
    environment:
      MP_DISABLE_VERSION_CHECK: "true"
    ports:
      - "1025:1025" # SMTP Server
      - "8025:8025" # UI
    healthcheck:
      <<: *healthcheck
      # health check see https://mailpit.axllent.org/docs/integration/healthcheck/
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8025/readyz" ]
    <<: *security_settings

networks:
  keycloak:
  minio:
