name: refarch-development-stack

x-healthcheck: &healthcheck
  interval: 30s
  timeout: 60s
  retries: 3
  start_period: 60s

x-security-settings: &security_settings
  security_opt:
    - no-new-privileges:true

services:
  # === Keycloak ===
  keycloak:
    image: quay.io/keycloak/keycloak:26.6.4@sha256:0aae0de7fca85525f727d3354df17896092de8bb26ae4c12d89c77e5df8cbce4
    command:
      - start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_HTTP_PORT: 8100
      KC_HTTP_RELATIVE_PATH: /auth
    ports:
      - "8100:8100"
    healthcheck:
      <<: *healthcheck
      test: [
        "CMD-SHELL",
        # health check see https://www.keycloak.org/observability/health#_healthcheck
        "{ printf 'HEAD /auth/health/ready HTTP/1.0\r\n\r\n' >&0; grep 'HTTP/1.0 200'; } 0<>/dev/tcp/localhost/9000"
      ]
    <<: *security_settings

  init-keycloak:
    image: klg71/keycloakmigration:0.3.1@sha256:9ddc34b452c29d00506bf4e935123a6bd354561ba87b84b2c3c760a13794d173
    depends_on:
      - keycloak
    environment:
      ADMIN_USER: admin
      ADMIN_PASSWORD: admin
      BASEURL: http://keycloak:8100/auth
      WAIT_FOR_KEYCLOAK: "true"
      FAIL_ON_UNDEFINED_VARIABLES: "true"
      KEYCLOAK_CHANGELOG: /migration/keycloak-changelog.yml
      EXIT_ON_ERROR: "true"
    volumes:
      - ./keycloak/migration:/migration
    <<: *security_settings

  # === S3 ===
  rustfs:
    image: rustfs/rustfs:1.0.0@sha256:8cc9801755448b71a786705ce76692c77e14936cccd87cf2fc31842e58f4d1ff
    environment:
      RUSTFS_ACCESS_KEY: admin
      RUSTFS_SECRET_KEY: admin
    ports:
      - "9000:9000" # API
      - "9001:9001" # UI
    volumes:
      - rustfs-data:/data
    healthcheck:
      <<: *healthcheck
      test: ["CMD", "curl", "-fsS", "http://localhost:9000/health/ready"]
    <<: *security_settings

  init-rustfs:
    image: rustfs/rc:v0.1.36@sha256:ab024bfebee49a750ce886b4c70963ccd9ddaa03f491704a90710641d7a26699
    depends_on:
      rustfs:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
        set -e;
        rc alias set local http://rustfs:9000 admin admin;
        rc mb local/test-bucket;
      "
    <<: *security_settings

  # === Mail ===
  mailpit:
    image: axllent/mailpit:v1.31.2@sha256:74d609a42ec279aa63c6b4622a6fa9b5408d1ad5b1d76a1c4be40a265ce0863d
    environment:
      MP_DISABLE_VERSION_CHECK: "true"
    ports:
      - "1025:1025" # SMTP Server
      - "8025:8025" # UI
    healthcheck:
      <<: *healthcheck
      # health check see https://mailpit.axllent.org/docs/integration/healthcheck/
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8025/readyz" ]
    <<: *security_settings

volumes:
  rustfs-data:
