name: refarch-development-stack

x-healthcheck: &healthcheck
  interval: 30s
  timeout: 60s
  retries: 3
  start_period: 60s

x-security-settings: &security_settings
  security_opt:
    - no-new-privileges:true

services:
  # === Keycloak ===
  keycloak:
    image: quay.io/keycloak/keycloak:26.6.4@sha256:0aae0de7fca85525f727d3354df17896092de8bb26ae4c12d89c77e5df8cbce4
    command:
      - start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_HTTP_PORT: 8100
      KC_HTTP_RELATIVE_PATH: /auth
    ports:
      - "8100:8100"
    networks:
      - keycloak
    healthcheck:
      <<: *healthcheck
      test: [
        "CMD-SHELL",
        # health check see https://www.keycloak.org/observability/health#_healthcheck
        "{ printf 'HEAD /auth/health/ready HTTP/1.0\r\n\r\n' >&0; grep 'HTTP/1.0 200'; } 0<>/dev/tcp/localhost/9000"
      ]
    <<: *security_settings

  init-keycloak:
    image: klg71/keycloakmigration:0.2.132@sha256:8251a3dd873dc0cd9bf5f6857385f77743a7d8e0a48b7d1cb16ad5ccf8cd1306
    depends_on:
      - keycloak
    environment:
      ADMIN_USER: admin
      ADMIN_PASSWORD: admin
      BASEURL: http://keycloak:8100/auth
      WAIT_FOR_KEYCLOAK: "true"
      FAIL_ON_UNDEFINED_VARIABLES: "true"
      KEYCLOAK_CHANGELOG: /migration/keycloak-changelog.yml
      EXIT_ON_ERROR: "true"
    volumes:
      - ./keycloak/migration:/migration
    networks:
      - keycloak
    <<: *security_settings

  # === S3 ===
  minio:
    image: quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z@sha256:14cea493d9a34af32f524e538b8346cf79f3321eff8e708c1e2960462bd8936e
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: Test1234
    ports:
      - "9000:9000" # API
      - "9001:9001" # UI
    volumes:
      - ./minio:/data
    networks:
      - minio
    healthcheck:
      <<: *healthcheck
      test: [ "CMD-SHELL",  "curl http://localhost:9000/minio/health/live" ]
    <<: *security_settings

  init-minio:
    image: quay.io/minio/mc:RELEASE.2025-08-13T08-35-41Z@sha256:a7fe349ef4bd8521fb8497f55c6042871b2ae640607cf99d9bede5e9bdf11727
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        mc config host add minio http://minio:9000 minio Test1234;
        mc mb minio/test-bucket;
        exit 0;
      "
    networks:
      - minio
    <<: *security_settings

  # === Mail ===
  mailpit:
    image: axllent/mailpit:v1.31.2@sha256:74d609a42ec279aa63c6b4622a6fa9b5408d1ad5b1d76a1c4be40a265ce0863d
    environment:
      MP_DISABLE_VERSION_CHECK: "true"
    ports:
      - "1025:1025" # SMTP Server
      - "8025:8025" # UI
    healthcheck:
      <<: *healthcheck
      # health check see https://mailpit.axllent.org/docs/integration/healthcheck/
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8025/readyz" ]
    <<: *security_settings

networks:
  keycloak:
  minio:
