spring:
  application:
    name: @project.artifactId@
    group: @project.groupId@
    version: @project.version@
  security:
    oauth2:
      client:
        provider:
          sso:
            issuer-uri: https://sso.example.com/auth/realms/refarch
        registration:
          cosys:
            provider: sso
            authorization-grant-type: client_credentials
            client-id: local
            client-secret: client_secret

logging:
  level:
    root: info
  structured:
    format:
      console: logstash
    json:
      stacktrace:
        root: first
        # default max size of one log line in docker is 16kb - UTF8 ~ 1 Character = 1 Byte
        # therefore limit stack traces to a maximum of 8192 characters (to leave room for the rest of the message)
        max-length: 8192
      add:
        application_name: ${spring.application.name}
        application_group: ${spring.application.group}

refarch:
  cosys:
    url: https://cosys.example.com/cosys-eai/rest
    merge:
      datafile: //multi
      inputLanguage: Deutsch
      outputLanguage: Deutsch
      keepFields: unresolved-ref
