refarch:
  s3:
    client:
      document-storage-url: http://localhost:8086
      enable-security: true
  cosys:
    url: https://cosysk007.srv.muenchen.de/cosys-eai/rest
    merge:
      datafile: //multi
      inputLanguage: Deutsch
      outputLanguage: Deutsch
      keepFields: unresolved-ref

SSO_S3_ISSUER_URL: http://keycloak:8100/auth/realms/local_realm
SSO_S3_CLIENT_ID: local
SSO_S3_CLIENT_SECRET: client_secret

SSO_COSYS_ISSUER_URL: http://keycloak:8100/auth/realms/local_realm
SSO_COSYS_CLIENT_ID: local
SSO_COSYS_CLIENT_SECRET: client_secret

server:
  port: 8093