spring:
  application:
    name: @project.artifactId@
    group: @project.groupId@
    version: @project.version@
  security:
    oauth2:
      client:
        provider:
          sso:
            issuer-uri: https://sso.example.com/auth/realms/refarch
        registration:
          cosys:
            provider: sso
            authorization-grant-type: client_credentials
            client-id: local
            client-secret: client_secret

logging:
  include-application-group: false # disabled because application group is only relevant when deployed
  level:
    root: INFO
    de.muenchen.refarch: DEBUG
    org.springframework.web: DEBUG

refarch:
  cosys:
    url: https://cosys.example.com/cosys-eai/rest
    merge:
      datafile: //multi
      inputLanguage: Deutsch
      outputLanguage: Deutsch
      keepFields: unresolved-ref
