refarch:
  s3:
    client:
      document-storage-url: http://localhost:8081
  cosys:
    merge:
      datafile: /root/multi
      inputLanguage: Deutsch
      outputLanguage: Deutsch
      keepFields: unresolved-ref
    ssoTokenClientId: digitalwf
