spring:
  security:
    oauth2:
      client:
        provider:
          sso:
            issuer-uri: https://sso.example.com/auth/realms/refarch
        registration:
          cosys:
            provider: sso
            authorization-grant-type: client_credentials
            client-id: local
            client-secret: client_secret

server:
  port: 8093

refarch:
  cosys:
    url: https://cosys.example.com/cosys-eai/rest
    merge:
      datafile: //multi
      inputLanguage: Deutsch
      outputLanguage: Deutsch
      keepFields: unresolved-ref
