spring:
  mail:
    host: localhost
    port: 1025
    username: test@muenchen.de
    password: secret

server:
  port: 8087

refarch:
  mail:
    from-address: test@muenchen.de
    default-reply-to-address: no_reply@muenchen.de
  s3:
    bucket-name: test-bucket
    access-key: minio
    secret-key: Test1234
    url: http://localhost:9000
