spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${refarch.security.sso-issuer-url}
            user-info-uri: ${refarch.security.sso-issuer-url}/protocol/openid-connect/userinfo
            jwk-set-uri: ${refarch.security.sso-issuer-url}/protocol/openid-connect/certs
            user-name-attribute: user_name
        registration:
          s3:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: ${refarch.s3.client.client-id}
            client-secret: ${refarch.s3.client.client-secret}
            scope: email, profile, openid  # needed for userInfo endpoint
