name: "Release Maven"
description: "Executes mvn release and creates a PR for the version change commits"

inputs:
  module:
    description: 'Module to build'
    required: true
  release-version:
    description: 'Release version'
    required: true
    default: "X.Y.Z"
  next-version:
    description: "Next version to use after release"
    required: true
    default: "X.Y.Z-SNAPSHOT"
  java-version:
    description: "Jave version used for building"
    required: false
    default: "21"
  gpg-private-key:
    description: "Gpg private key used for signing packages for maven central release"
    required: true
  gpg-passphrase:
    description: "Gpg passphrase for private key"
    required: true
  sonatype-username:
    description: "Sonatype username for maven central release"
    required: true
  sonatype-password:
    description: "Sonatype password for maven central release"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up JDK
      uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
      with:
        java-version: ${{ inputs.java-version }}
        distribution: "temurin"
        cache: "maven"
        cache-dependency-path: "./${{ inputs.module }}/pom.xml"
        server-id: "central"
        server-username: CENTRAL_USERNAME
        server-password: CENTRAL_PASSWORD
        gpg-private-key: ${{ inputs.gpg-private-key }}
        gpg-passphrase: SIGN_KEY_PASS
    - name: Maven release
      shell: bash
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        mvn release:prepare -f ./${{ inputs.module }}/pom.xml -B -DreleaseVersion=${{ inputs.release-version }} -DdevelopmentVersion=${{ inputs.next-version }} -DpushChanges=false -DremoteTagging=false
        mvn release:perform -f ./${{ inputs.module }}/pom.xml -DlocalCheckout=true
      env:
        SIGN_KEY_PASS: ${{ inputs.gpg-passphrase }}
        CENTRAL_USERNAME: ${{ inputs.sonatype-username }}
        CENTRAL_PASSWORD: ${{ inputs.sonatype-password }}
    - name: "Upload target artifacts"
      uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
      with:
        name: target
        path: "**/target"
        retention-days: 5
    - name: Push changes to new branch
      shell: bash
      run: |
        git checkout -b ${{ inputs.module }}-version-bump
        git push --force origin ${{ inputs.module }}-version-bump
    - name: Create pull request
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          const { repo, owner } = context.repo;
          const pullResult = await github.rest.pulls.create({
            title: 'chore: bump release version ${{ inputs.module }}',
            owner,
            repo,
            head: '${{ inputs.module }}-version-bump',
            base: '${{ github.ref_name }}',
            body: [
              'This PR is auto-generated'
            ].join('\n')
          });
          await github.rest.issues.addAssignees({
            owner,
            repo,
            issue_number: pullResult.data.number,
            assignees: ['${{ github.actor }}'],
          });
          console.log(`Pull Request created: ${pullResult.data.html_url}`);
