info:
  application:
    name: '@project.artifactId@'
    version: '@project.version@'

spring:
  application:
    name: ${info.application.name}
  cloud:
    stream:
      bindings:
        functionRouter-in-0:
          group: "dwf-s3-service"
          destination: dwf-s3-${DIGIWF_ENV}
        sendMessage-out-0:
          destination: dwf-connector-${DIGIWF_ENV}

server:
  error:
    include-exception: false
    include-stacktrace: never
    whitelabel:
      enabled: false
  shutdown: graceful

# Config for spring actuator endpoints
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, prometheus, livenessstate, readinessstate
      path-mapping:
        prometheus: metrics
  endpoint:
    health.enabled: true
    info.enabled: true
    prometheus.enabled: true

digiwf:
  security:
    client-id: ${SSO_S3_CLIENT_ID}
    client-secret: ${SSO_S3_CLIENT_SECRET}
refarch:
  s3:
    bucket-name: ${S3_BUCKETNAME}
    access-key: ${S3_ACCESSKEY}
    url: ${S3_URL:http://localhost:9000}
    secret-key: ${S3_SECRETKEY}
