spring:
  application:
    name: @project.artifactId@
    group: @project.groupId@
    version: @project.version@
  mail:
    host: localhost
    port: 1025
    username: test@muenchen.de
    password: secret

server:
  port: 8087

logging:
  level:
    root: info
  structured:
    format:
      console: logstash
    json:
      stacktrace:
        root: first
        # default max size of one log line in docker is 16kb - UTF8 ~ 1 Character = 1 Byte
        # therefore limit stack traces to a maximum of 8192 characters (to leave room for the rest of the message)
        max-length: 8192
      add:
        application_name: ${spring.application.name}
        application_group: ${spring.application.group}

refarch:
  mail:
    from-address: test@muenchen.de
    default-reply-to-address: no_reply@muenchen.de
