spring:
  application:
    name: "@project.artifactId@"
    group: "@project.groupId@"
    version: "@project.version@"
  mail:
    host: localhost
    port: 1025
    username: test@muenchen.de
    password: secret

server:
  port: 8087

logging:
  include-application-group: false # disabled because application group is only relevant when deployed
  level:
    root: INFO
    de.muenchen.refarch: DEBUG
    org.springframework.web: DEBUG

refarch:
  mail:
    from-address: test@muenchen.de
    default-reply-to-address: no_reply@muenchen.de
