name: build

on:
  pull_request:
  push:

jobs:
  maven:
    uses: ./.github/workflows/maven.yaml
    with:
      build-images: ${{ github.ref_name == 'main' }}
      release-version: dev
    secrets: inherit
