name: build-gateway

on:
  pull_request:
    paths:
      - refarch-gateway/**
  push:
    branches:
      - main

jobs:
  maven:
    uses: ./.github/workflows/maven.yaml
    with:
      module: refarch-gateway
      build-images: ${{ github.ref_name == 'main' }}
      release-version: dev
    secrets: inherit
