name: Deploy docs

on:
  push:
    paths:
      - "docs/**"
      - ".github/workflows/**"

  workflow_dispatch:

jobs:
  deploy-pages:
    uses: it-at-m/.github/.github/workflows/deploy-pages.yml@main
