name: Docker Compose Healthcheck

on:
  # Runs on pull requests
  pull_request:

jobs:
  docker-compose-healthcheck:
    name: Run docker compose healthcheck
    runs-on: ubuntu-latest
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-dockercompose-healthcheck@17061b55c5c6df8fa9934d6488d7d29781c24343 # v1.0.14
        with:
          skip-exited: true # required for keycloakmigration init container
          compose-file-path: "./stack/"