# Workflow to check health of dockercompose based development stacks
name: dockercompose-healthcheck

on:
  pull_request:

jobs:
  dockercompose-healthcheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-dockercompose-healthcheck@fix/218-healthccheck-action
        with:
          compose-file-path: "./stack/"