name: Validate PR checklist

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]

jobs:
  pr-checklist:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-pr-checklist@a7d25dbabec2057695f865169fdc411d475d4667 # v1.0.19
