# Workflow to release artifacts and images
name: release

on:
  workflow_dispatch:
    inputs:
      module:
        description: 'Module to release'
        type: choice
        required: true
        options:
          - refarch-gateway
          - refarch-integrations
          - refarch-tools/refarch-java-tools
      release-version:
        description: 'Release version'
        type: string
        required: true
        default: "X.Y.Z"
      next-version:
        description: "Next version to use after release"
        type: string
        required: true
        default: "X.Y.Z-SNAPSHOT"
      tag-latest:
        type: boolean
        description: "Tag images with latest"
        required: true
        default: true

jobs:
  release-maven:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      MVN_ARTIFACT_ID: ${{ steps.release-maven.outputs.MVN_ARTIFACT_ID }}
      ARTIFACT_NAME: ${{ steps.release-maven.outputs.artifact-name }}
    steps:
      - id: release-maven
        uses: it-at-m/lhm_actions/action-templates/actions/action-maven-release@acb09213786b76dd7aa52ec1d901390d28c60eb0 # v1.0.29
        with:
          app-path: ${{ inputs.module }}
          java-version: "21"
          releaseVersion: ${{ inputs.release-version }}
          developmentVersion: ${{ inputs.next-version }}
          use-pr: true
          skipDeployment: false
          SIGN_KEY_PASS: ${{ secrets.gpg_passphrase }}
          CENTRAL_USERNAME: ${{ secrets.sonatype_username }}
          CENTRAL_PASSWORD: ${{ secrets.sonatype_password }}
          GPG_PRIVATE_KEY: ${{ secrets.gpg_private_key }}

  release-image-gateway:
    if: inputs.module == 'refarch-gateway'
    needs: release-maven
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-build-image@acb09213786b76dd7aa52ec1d901390d28c60eb0 # v1.0.29
        with:
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          path: ./refarch-gateway
          artifact-name: ${{ needs.release-maven.outputs.ARTIFACT_NAME }}
          image-name: refarch-gateway
          image-tags: |
            type=raw,value=${{ inputs.release-version }}
            type=raw,value=latest,enable=${{ inputs.tag-latest == true }}

  release-github:
    if: ${{ !failure() && !cancelled() }}
    needs: ["release-maven", "release-image-gateway"]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-create-github-release@acb09213786b76dd7aa52ec1d901390d28c60eb0 # v1.0.29
        with:
          tag-name: "${{ inputs.module }}_${{ github.event.inputs.release-version }}"
          generate-release-notes: true
          artifact-name: ${{ needs.release-maven.outputs.ARTIFACT_NAME }}
          artifact-path: |
            ./refarch-gateway/target/*.jar
