# Workflow to retag an existing docker image
name: retag-image

on:
  workflow_dispatch:
    inputs:
      image-name:
        description: 'Image name'
        type: string
        required: true
      existing-tag:
        description: 'Existing tag'
        type: string
        required: true
      new-tag:
        description: 'New tag'
        type: string
        required: true
        default: "latest"

jobs:
  retag-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-checkout@877aafa9f0732cbc91819b60d237c351ea88f95c # v1.0.34
      - uses: ./.github/actions/retag-image
        with:
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          image-name: ${{ inputs.image-name }}
          existing-tag: ${{ inputs.existing-tag }}
          new-tag: ${{ inputs.new-tag }}
