name: test

on:
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - run: |
         cd lhm_actions
         cd ..
         cd docs/templates
         ls 
         cd docs
         ls
