spring:
  application:
    name: "@project.artifactId@"
    group: "@project.groupId@"
    version: "@project.version@"

logging:
  include-application-group: false # disabled because application group is only relevant when deployed
  level:
    root: INFO
    de.muenchen.refarch: DEBUG
    org.springframework.web: DEBUG

refarch:
  dms:
    fabasoft:
      businessapp: refarch-example
      url:
      ui-url:
      username:
      password:
    example:
      username:
      target-procedure-coo:
